### ISSUE TITLE
prokka: home directory is owned by root

### ISSUE THREAD

**Issue by audy** [sjackman/docker-bio#1]
`docker run --entrypoint /bin/ls sjackman/prokka -lash /home`

Gives me:

```
4.0K drwxr-xr-x 11 root root 4.0K Nov 13 14:37 .
4.0K drwxr-xr-x 68 root root 4.0K Jan 29 19:51 ..
4.0K drwxr-xr-x 20 root root 4.0K Nov 13 14:37 linuxbrew
```

And running `sudo` asks for a password.

This is odd given that the parent image `sjackman/linuxbrew` does not.

(note: this is the version on Dockerhub).

**Comment by audy** [comment]
selab.janelia.org is down for me or I'd try building it myself.

**Comment by sjackman** [comment]
The last time `sjackman/prokka` was built was [over a year ago](https://hub.docker.com/r/sjackman/prokka/builds/). I'll rebuild it now. That should hopefully fix your issue, since it's already resolved in the parent image.

**Comment by audy** [comment]
[Build failed installing infernal](https://hub.docker.com/r/sjackman/prokka/builds/bdxafp54rxjxj3srajkmech/). Looks like selab is still down. Do you know of another place to get Infernal? Maybe I can change the homebrew recipe to pull from a GitHub release or something.

**Comment by sjackman** [comment]
One fix is to upload a copy of the tarball, if you can find one, to some other server (like Bintray) and edit the formula to use that mirror.

**Comment by sjackman** [comment]
It looks like `infernal` has moved to http://eddylab.org/software/infernal/infernal-1.1.1.tar.gz

**Comment by sjackman** [comment]
I've updated the `infernal` formula. Rebuilding `sjackman/prokka`.

**Comment by sjackman** [comment]
BLAST failed to install. I don't have a quick fix for this error.
https://hub.docker.com/r/sjackman/prokka/builds/bhxep8hnlalhbq49dv4ze96/

```
Updating dependency information for /tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/src/corelib/test_boost.cpp.
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/src/corelib/test_boost.cpp:73:40: fatal error: boost/test/test_observer.hpp: No such file or directory
 #include <boost/test/test_observer.hpp>
                                        ^
compilation terminated.
FAILED COMMAND:  /usr/bin/g++-4.8  -std=gnu++11 -M  -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE  -isystem/home/linuxbrew/.linuxbrew/include -D_MT -D_REENTRANT -D_THREAD_SAFE -I/tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/ReleaseMT/inc -I/tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/include  -Wno-unused-local-typedefs /tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/src/corelib/test_boost.cpp  | sed ...
make[3]: Leaving directory `/tmp/blast20160130-20924-14k5vwr/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
```

**Comment by sjackman** [comment]
The same error has been reported over here: https://bugzilla.redhat.com/show_bug.cgi?id=1259781

**Comment by audy** [comment]
What do you think about installing BLAST with apt-get instead of Homebrew? Compiling takes forever...

**Comment by sjackman** [comment]
You could certainly do that on your own system. Remove the `blast` dependency from `prokka`, `apt-get install blast`, and it should work. Linuxbrew will continue to compile BLAST from source.

**Comment by audy** [comment]
Working on my own Docker image for Prokka.

FYI - Prokka comes bundled with linux binaries for blast, hmmer, prodigal, and aragorn.

**Comment by sjackman** [comment]
The issue for tracking the BLAST installation error is over here:
https://github.com/Homebrew/homebrew-science/issues/2705

**Comment by tseemann** [comment]
The `selab` website issue was to do with `trnascan` which moved websites - this was fixed in the homebrew-science formula.

**Comment by sjackman** [comment]
I believe that BLAST still doesn't build on Linuxbrew. It would be nice to fix that.
